[tool.poetry]
name = "mimesis-demo"
version = "0.1.0"
description = ""
authors = ["nakaken <k.nakagaki@churadata.okinawa>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
